name: 构建镜像

on:
  workflow_dispatch:
    inputs:
      packagefile_name:
        description: '包路径'
      dockerfile_path:
        description: 'dockerfile path'
        default: 'Dockerfile'
      server_name:
        description: '服务名称'
#       tag_name:
#         description: '镜像tag'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        wget ${{ github.event.inputs.packagefile_name }} -O ${{ github.event.inputs.server_name }}.zip
        unzip ${{ github.event.inputs.server_name }}.zip
        cd wordpress-master/latest
        for i in `find ${{ github.event.inputs.dockerfile_path }} -name Dockerfile|grep -v fpm-a|xargs dirname`;do cd $i &&test=`echo $i|awk -F '/' '{print $NF}'` && docker build -t ${{ github.event.inputs.dockerfile_path }}/$test:v1  . && cd -;done
        
