name: docker netshoot multi

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 拉取代码
      run: |
        ls /home/runner/work/linux/centos
        exit
        docker login -u ${{ secrets.ALI_USER}} -p ${{ secrets.ALI_PASSWORD}} registry.cn-hangzhou.aliyuncs.com/duxiao
        git clone https://github.com/nicolaka/netshoot.git
        cd netshoot
        mv ../centos/ssh-server/Dockerfile-net-sshd Dockerfile
        wget https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64
        mv buildx-v0.7.1.linux-amd64 docker-buildx
        mkdir ~/.docker/cli-plugins/
        mv docker-buildx ~/.docker/cli-plugins/docker-buildx
        chmod +x ~/.docker/cli-plugins/docker-buildx
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx version
        docker buildx create --use --name mybuilder
        docker buildx ls
        docker buildx build -t registry.cn-hangzhou.aliyuncs.com/duxiao/netshoot:v1.2 --platform=linux/arm64,linux/amd64,linux/arm/v7 .  --push
    - name: test
      run: echo test
