name: docker netshoot multi

on: 
  workflow_dispatch:
    inputs:
      cpu_architecture:
        description: 'cpu架构'
        default: 'linux/amd64'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 拉取代码
      run: |
        pwd
        ls /home/runner/work/linux/linux
        docker login -u ${{ secrets.ALI_USER}} -p ${{ secrets.ALI_PASSWORD}} registry.cn-hangzhou.aliyuncs.com/duxiao
        git clone https://github.com/nicolaka/netshoot.git
        cd netshoot
        mv ../centos/ssh-server/Dockerfile-net-sshd Dockerfile
        mv ../centos/ssh-server/entrypoint.sh entrypoint.sh
        mv ../centos/ssh-server/sshd_config sshd_config
        wget https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64
        mv buildx-v0.7.1.linux-amd64 docker-buildx
        mkdir ~/.docker/cli-plugins/
        mv docker-buildx ~/.docker/cli-plugins/docker-buildx
        chmod +x ~/.docker/cli-plugins/docker-buildx
        docker run --privileged --rm tonistiigi/binfmt --install all /dev/null 2>&1
        docker buildx version
        echo "=================================================="
        docker buildx create --use --name mybuilder
        docker buildx ls
        echo "=================================================="
        docker buildx build -t registry.cn-hangzhou.aliyuncs.com/duxiao/netshoot:v1.2 --platform=${{ github.event.inputs.cpu_architecture }} .  --push
        docker images
        ls ./*


