
name: docker build 

on:
  push:
    paths:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: pull
      run: |
        docker build -f centos/docker/dockerfile/Dockerfile-jenkins -t jenkins:v1 .
        docker save jenkins:v1 -o jenkins.tar
        mkdir artifacts
        mv jenkins.tar artifacts/
        
       
    - uses: actions/upload-artifact@v2
      with: 
        name: artifacts
        path:  artifacts/*
