
name: docker build 

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/**'
  
    
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: pull
      run: |
        docker login -u ${{ secrets.DOCKER_USER}} -p ${{ secrets.DOCKER_PASSWORD}} docker.io
        docker build -f centos/docker/dockerfile/Dockerfile-jenkins -t 9512220/jenkins:jenkins-python3 .
        docker push 9512220/jenkins:jenkins-python3
        #mkdir artifacts
        #mv jenkins.tar artifacts/
        
       
#     #- uses: actions/upload-artifact@v2
#       with: 
#         name: artifacts
#         path:  artifacts/*
