
name: 构建docker镜像

on:
  workflow_dispatch:     
    inputs:
      oldimage_name:
        description: '旧镜像名称'
      imges_url:
        description: '镜像仓库'
        default: '9512220'
      server_name:
        description: '服务名称'
      tag_name:
        description: '镜像tag'
        
        
#       logLevel:
#         description: 'Log level'     
#         required: true
#         default: 'warning'
#       tags:
#         description: 'Test scenario tags' 

#   push:
#     paths:
#       - '.github/workflows/**'



jobs:

#   printInputs:
#     runs-on: ubuntu-18.04
#     steps:
#     - run: |
#         echo "Log level: ${{ github.event.inputs.logLevel }}"
#         echo "Tags: ${{ github.event.inputs.tags }}"
        
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: pull
      run: |
        docker login -u ${{ secrets.DOCKER_USER}} -p ${{ secrets.DOCKER_PASSWORD}} docker.io
        docker pull ${{ github.event.inputs.oldimage_name }}
        docker tag ${{ github.event.inputs.oldimage_name }}  ${{ github.event.inputs.imges_url }}/${{ github.event.inputs.server_name }}:${{ github.event.inputs.tag_name }}
        docker  push ${{ github.event.inputs.imges_url }}/${{ github.event.inputs.server_name }}:${{ github.event.inputs.tag_name }}
        #mkdir artifacts
        #mv jenkins.tar artifacts/

        
#     #- uses: actions/upload-artifact@v2
#       with: 
#         name: artifacts
#         path:  artifacts/*


#   job1:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "job1"
#   job2:
#     runs-on: ubuntu-latest
#     steps:
#       - run: sleep 5
#     needs: job1
#   job3:
#     runs-on: ubuntu-latest
#     steps:
#       - run: sleep 10
#     needs: job1
#   job4:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "job4"
#     needs: [job2, job3]
