
name: docker build 

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/**'
  
    
jobs:

  printInputs:
    runs-on: ubuntu-18.04
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
        
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: pull
      run: |
        docker login -u ${{ secrets.DOCKER_USER}} -p ${{ secrets.DOCKER_PASSWORD}} docker.io
        docker pull k8s.gcr.io/descheduler/descheduler:v0.22.0
        docker tag k8s.gcr.io/descheduler/descheduler:v0.22.0 9512220/k8s-descheduler:v0.22.0
        docker  push 9512220/k8s-descheduler:v0.22.0
        #mkdir artifacts
        #mv jenkins.tar artifacts/


        
#     #- uses: actions/upload-artifact@v2
#       with: 
#         name: artifacts
#         path:  artifacts/*
