# https://docs.github.com/en/actions

name: "Release"

on:
  workflow_dispatch:     
    inputs:
      linshi_name:
        description: 'test'
jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Determine tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"

      - name: "Create release"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.GAP }}"
          script: |
            curl -X POST -H "Accept: application/vnd.github.v3+json"  -H "Authorization: token ${{ secrets.GAP }}"  https://api.github.com/repos/jafardu/linux/releases/001/assets             -d '{"name":"README.md","label":"test pkg"}'
