name: yum源制作
on:
  workflow_dispatch:     
    inputs:
      demo_name:
        description: '项目名称'
jobs:     
  epel:
    name: 下载yum源
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: run centos7.9
      run: |
        pwd
        ls -l
        docker run --name centos  -itd centos:centos7
        docker exec centos yum -y install  createrepo
        docker exec centos yum -y install epel-release
        docker cp yum.sh centos:/opt/yum.sh
        docker exec centos bash /opt/yum.sh
        docker cp /opt/yum.tar.gz yum.tar.gz
        mkdir artifacts
        mv *.tar.gz artifacts/
        
    - uses: actions/upload-artifact@v2
      with: 
        name: artifacts
        path:  artifacts/*
