name: 执行命令
on:
  workflow_dispatch:
    inputs:
      command1:
        description: '基础命令1'
        default: 'sleep 1'
      command2:
        description: '基础命令2'
        default: 'sleep 1'
      artifacts:
        description: '将结果保存到artifacts目录'
        default: 'artifacts'

jobs:
  run-command:
    name: 执行命令
    runs-on: ubuntu-latest
    steps:
    - name: 创建制品文件保存的目录
      run: mkdir ${{ inputs.artifacts }}
    - name: run command1
      run: ${{ inputs.command1 }}
    - name: run command2
      run: ${{ inputs.command2 }}

    - uses: actions/download-artifact@v2.1.1
      with: 
        name: artifacts
        path:  ${{ inputs.artifacts }}/*
