name: 执行命令
on:
  workflow_dispatch:
    inputs:
      command1:
        description: '基础命令1'
        default: 'echo -e "FROM alpine:3.16.2\nRUN echo \"@testing http://nl.alpinelinux.org/alpine/edge/testing\" >> /etc/apk/repositories\nRUN apk add --no-cache bash cfssl@testing\nEXPOSE 8888\nCMD [\"cfssl\"]">Dockerfile'
      command2:
        description: '基础命令2'
        default: 'docker build -t cfssl:v1 . && docker save cfssl:v1 -o artifacts/cfssl.tar'
      artifacts:
        description: '将结果保存到artifacts目录'
        default: 'artifacts'

jobs:
  run-command:
    name: 执行命令
    runs-on: ubuntu-latest
    steps:
    - name: 创建制品文件保存的目录
      run: mkdir ${{ inputs.artifacts }}
    - name: run command1
      run: ${{ inputs.command1 }}
    - name: run command2
      run: ${{ inputs.command2 }}

    - uses: actions/download-artifact@v2.1.1
      with: 
        name: artifacts
        path:  ${{ inputs.artifacts }}/*
