name: 下载制品到Runner

on:
  workflow_run:
    workflows: ["pull"]
    types:
      - completed

jobs:
  download:
    runs-on: self-hosted
    # 仅当上游流水线成功时执行
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: test
          path: ./artifacts

      - name: 查看下载内容
        run: ls ./artifacts
