name: 下载制品到Runner

on:
  workflow_run:
    workflows: ["pull"]
    types:
      - completed

jobs:
  download:
    runs-on: self-hosted
    # 仅当上游流水线成功时执行
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 获取 Artifacts 下载 URL
        shell: powershell
        run: |
          # $artifact_url = "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts"
          # Write-Output "Fetching artifacts from: $artifact_url"
          $artifactsUrl = Invoke-RestMethod -Uri "https://api.github.com/repos/linux/galendu/actions/workflows/muliti-image.yml/runs" `
              -Headers $headers | Select-Object -ExpandProperty workflow_runs | Select-Object -First 1 -ExpandProperty artifacts_url
          $headers = @{
            Authorization = "Bearer ${{ secrets.LINSHI_TOKEN }}"
            Accept = "application/vnd.github+json"
          }
          echo $artifactsUrl
          # 下载制品
          $artifacts = Invoke-RestMethod -Uri $artifactsUrl -Headers $headers
          $artifacts.artifacts | ForEach-Object {
              $url = $_.archive_download_url
              Invoke-WebRequest -Uri $url -Headers $headers -OutFile "test.zip"
          }
