name: 下载制品到Runner

on:
  workflow_run:
    workflows: ["拉取镜像到本地"]
    types:
      - completed

jobs:
  download:
    runs-on: self-hosted
    # 仅当上游流水线成功时执行
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: 下载 artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: ./downloaded
      - name: 查看下载内容
        run: ls -al ./downloaded
